/**
 * Legal Disclaimer Component
 *
 * Displays financial advice disclaimer on all pages with financial data.
 * Based on TRUTH_FREE.md Phase 2.1 specifications.
 */

export const LegalDisclaimer = () => (
  <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-6 rounded-r-lg shadow-sm">
    <div className="flex">
      <div className="flex-shrink-0">
        <svg
          className="h-5 w-5 text-yellow-400"
          viewBox="0 0 20 20"
          fill="currentColor"
          aria-hidden="true"
        >
          <path
            fillRule="evenodd"
            d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
            clipRule="evenodd"
          />
        </svg>
      </div>
      <div className="ml-3">
        <h3 className="text-sm font-medium text-yellow-800">
          Important Legal Disclaimer
        </h3>
        <div className="mt-2 text-sm text-yellow-700 space-y-2">
          <p>
            <strong>NOT FINANCIAL ADVICE:</strong> This application is for educational and informational purposes only.
            Nothing on this site constitutes investment advice, financial advice, trading advice, or any other sort of advice.
            You should not treat any content as such.
          </p>
          <p>
            <strong>DO YOUR OWN RESEARCH:</strong> Always conduct your own research and consult with a licensed
            financial advisor before making any investment decisions. Past performance does not guarantee future results.
            Trading stocks involves substantial risk of loss.
          </p>
          <p>
            <strong>DATA ACCURACY:</strong> While we strive for accuracy, we do not guarantee the completeness,
            accuracy, reliability, or timeliness of any information displayed on this site.
            Stock prices may be delayed up to 15 seconds or more.
          </p>
          <p>
            <strong>NO LIABILITY:</strong> We are not responsible for any investment decisions you make based
            on information from this site. Use this tool at your own risk.
          </p>
        </div>
      </div>
    </div>
  </div>
);


/**
 * Educational Use Banner Component
 *
 * Displays educational use disclaimer for data sources.
 */
export const EducationalBanner = () => (
  <div className="bg-blue-50 border-l-4 border-blue-400 p-3 mb-4 rounded-r-lg">
    <div className="flex items-center">
      <svg
        className="h-5 w-5 text-blue-400 mr-2"
        fill="currentColor"
        viewBox="0 0 20 20"
        aria-hidden="true"
      >
        <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
        <path
          fillRule="evenodd"
          d="M10 18a8 8 0 100-16 8 8 0 000 16zm0-2a6 6 0 100-12 6 6 0 000 12z"
          clipRule="evenodd"
        />
      </svg>
      <p className="text-sm text-blue-700">
        <strong>Educational Use Only:</strong> This project uses Yahoo Finance data for educational
        and portfolio demonstration purposes only. Not licensed for commercial use.
      </p>
    </div>
  </div>
);


/**
 * Data Source Disclosure Component
 *
 * Shows transparency about data sources and accuracy.
 */
interface DataSourceDisclosureProps {
  isMarketOpen?: boolean;
}

export const DataSourceDisclosure = ({ isMarketOpen = false }: DataSourceDisclosureProps) => (
  <div className="text-xs text-gray-500 mt-4 p-3 bg-gray-50 rounded border border-gray-200">
    <p className="font-semibold mb-1">Data Source Disclosure:</p>
    <ul className="space-y-1">
      <li>• <strong>Stock Prices:</strong> Provided by Yahoo Finance (delayed up to 15 seconds)</li>
      <li>• <strong>Company Filings:</strong> SEC EDGAR database (public domain)</li>
      <li>• <strong>AI Insights:</strong> Generated by Google Gemini 2.0 Flash (experimental)</li>
      <li>• <strong>Market Status:</strong> US stock market (NYSE, NASDAQ) trading hours</li>
      <li>• <strong>Data Delay:</strong> Prices are NOT real-time. This is NOT Level 1 or Level 2 market data.</li>
    </ul>
    <p className="mt-2 font-semibold">
      Last Updated: {new Date().toLocaleTimeString()}
      {' '}
      {isMarketOpen ? (
        <span className="text-green-600">(Market OPEN)</span>
      ) : (
        <span className="text-red-600">(Market CLOSED)</span>
      )}
    </p>
  </div>
);
